# Generated by Django 3.1.4 on 2020-12-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haikuApp', '0002_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
    ]
