# Generated by Django 3.1.4 on 2020-12-20 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haikuApp', '0003_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_id',
        ),
    ]
